# Generated by Django 5.2.13 on 2026-04-28

import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("party_size", models.PositiveSmallIntegerField()),
                ("status", models.CharField(default="pending_review", max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("staff_message", models.TextField(blank=True)),
                ("payment_due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.customer",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="memberships.staffmembership",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status", "starts_at"], name="bookings_bo_status_67aa67_idx")],
            },
        ),
    ]
