# Generated by Django 5.2.13 on 2026-04-28

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_room_table"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "pending_review"),
                    ("pending_payment", "pending_payment"),
                    ("confirmed", "confirmed"),
                    ("confirmed_without_deposit", "confirmed_without_deposit"),
                    ("declined", "declined"),
                    ("cancelled_by_customer", "cancelled_by_customer"),
                    ("cancelled_by_staff", "cancelled_by_staff"),
                    ("no_show", "no_show"),
                    ("expired", "expired"),
                    ("authorization_expired", "authorization_expired"),
                ],
                default="pending_review",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurants.table",
            ),
        ),
    ]
