# Generated by Django 5.2.13 on 2026-04-29

import django.db.models.deletion
import uuid

from django.db import migrations, models


def copy_booking_tables(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    BookingTableAssignment = apps.get_model("bookings", "BookingTableAssignment")

    assignments = [
        BookingTableAssignment(booking_id=booking.id, table_id=booking.table_id)
        for booking in Booking.objects.exclude(table_id__isnull=True).only("id", "table_id")
    ]
    BookingTableAssignment.objects.bulk_create(assignments, ignore_conflicts=True)


def restore_booking_tables(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    BookingTableAssignment = apps.get_model("bookings", "BookingTableAssignment")

    for assignment in BookingTableAssignment.objects.order_by("created_at").only(
        "booking_id", "table_id"
    ):
        Booking.objects.filter(pk=assignment.booking_id, table_id__isnull=True).update(
            table_id=assignment.table_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_walkin"),
        ("memberships", "0001_initial"),
        ("restaurants", "0003_room_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingTableAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="memberships.staffmembership",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_assignments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_assignments",
                        to="restaurants.table",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookingtableassignment",
            constraint=models.UniqueConstraint(
                fields=("booking", "table"),
                name="uniq_booking_table_assignment",
            ),
        ),
        migrations.RunPython(copy_booking_tables, restore_booking_tables),
        migrations.RemoveField(model_name="booking", name="table"),
    ]
