# Generated by Django 5.2.13 on 2026-04-29

import django.db.models.deletion
import uuid

from django.db import migrations, models


def copy_walkin_tables(apps, schema_editor):
    Walkin = apps.get_model("bookings", "Walkin")
    WalkinTableAssignment = apps.get_model("bookings", "WalkinTableAssignment")

    assignments = [
        WalkinTableAssignment(walkin_id=walkin.id, table_id=walkin.table_id)
        for walkin in Walkin.objects.exclude(table_id__isnull=True).only("id", "table_id")
    ]
    WalkinTableAssignment.objects.bulk_create(assignments, ignore_conflicts=True)


def restore_walkin_tables(apps, schema_editor):
    Walkin = apps.get_model("bookings", "Walkin")
    WalkinTableAssignment = apps.get_model("bookings", "WalkinTableAssignment")

    for assignment in WalkinTableAssignment.objects.order_by("created_at").only(
        "walkin_id", "table_id"
    ):
        Walkin.objects.filter(pk=assignment.walkin_id, table_id__isnull=True).update(
            table_id=assignment.table_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_table_assignment"),
        ("memberships", "0001_initial"),
        ("restaurants", "0003_room_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalkinTableAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="memberships.staffmembership",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walkin_assignments",
                        to="restaurants.table",
                    ),
                ),
                (
                    "walkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_assignments",
                        to="bookings.walkin",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="walkintableassignment",
            constraint=models.UniqueConstraint(
                fields=("walkin", "table"),
                name="uniq_walkin_table_assignment",
            ),
        ),
        migrations.RunPython(copy_walkin_tables, restore_walkin_tables),
        migrations.RemoveField(model_name="walkin", name="table"),
    ]
