# Generated by Django 5.2.13 on 2026-04-28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deposit_policy",
                    models.CharField(
                        choices=[
                            ("never", "never"),
                            ("always", "always"),
                            ("party_threshold", "party_threshold"),
                        ],
                        default="never",
                        max_length=32,
                    ),
                ),
                ("deposit_party_threshold", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("deposit_amount_cents", models.PositiveIntegerField(default=0)),
                ("near_term_threshold_hours", models.PositiveSmallIntegerField(default=48)),
                ("long_term_payment_window_hours", models.PositiveSmallIntegerField(default=24)),
                ("cancellation_cutoff_hours", models.PositiveSmallIntegerField(default=24)),
                ("booking_cutoff_minutes", models.PositiveSmallIntegerField(default=5)),
                ("advance_booking_days", models.PositiveSmallIntegerField(default=90)),
            ],
        ),
    ]
